#!/usr/bin/env node

"use strict"

const webpack = require("webpack");

const paths = require("../config/paths");
const config = require("../config/webpack.prod");

var ProgressBar = require("ascii-progress");
const formatMessage = require("react-dev-utils/formatWebpackMessages");

const bar = new ProgressBar({
	schema: "[:bar].green \t:current/:total.bold.cyan \t:percent.bold.cyan \t:elapseds.bold.red :etas.bold.red",
	total : 100
});

const progressHandler = (percentage) => {
	bar.tick(Math.round(percentage * 100));
};

const progress = new webpack.ProgressPlugin(progressHandler);

config.plugins.push(progress);

function start() {

	build()
	.then(() => {})
	.catch(e => {
		console.error(e)
	})

}

function build() {
	const compiler = webpack(config);

	return new Promise((resolve, reject) => {

		compiler.run((error, stats) => {

			if(error) {
				reject(error);
			}

			const messages = formatMessage(stats.toJson({},true));

			if (messages.errors.length) {

				if (messages.errors.length > 1) {
					messages.errors.length = 1;
				}
				return reject(new Error(messages.errors.join("\n\n")));
			}
			return resolve({
				stats,
				warnings: messages.warnings,
			});

		});

	});
}

start();